### ISSUE TITLE
etcd-browser - crashes if not accessible...

### ISSUE THREAD

**Issue by ajohnstone** [henszey/etcd-browser#10]
```
etcd-browser master → docker logs 8ce97cda4329a44cca9c2a4ae461707ff2a09dd71196558eb4445138ed57005a
proxy /api requests to etcd on 172.17.42.1:5001:4001
etc-browser listening on port 8000

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
```

**Comment by drinktee** [comment]
I have the same problem

**Comment by harder-worker** [comment]
you have to modify to the file of server.js,and add to the path of ETCDCTL_CA_FILE ETCDCTL_KEY_FILE ETCDCTL_CERT_FILE
