### ISSUE TITLE
Request failed - - http://192.168.134.129:4001/v2/keys/

### ISSUE THREAD

**Issue by hsluoyz** [henszey/etcd-browser#20]
Hi.

I have an etcd 2.3.1 cluster with Kubernetes 1.2.4 on my Ubuntu 14.04 x64 VM. 

Here's the status:

```
root@ubuntu:/kubernetes/cluster# etcdctl cluster-health
member ce2a822cea30bfca is healthy: got healthy result from http://192.168.134.129:4001
cluster is healthy
```

Then I browsed to `http://henszey.github.io/etcd-browser/` in this VM's firefox, entered `http://192.168.134.129:4001` and click `Go!`. It gave me: 

`Request failed - - http://192.168.134.129:4001/v2/keys/`

But when I opened the `http://192.168.134.129:4001/v2/keys/` address in another tab of my Firefox, it shows normally:

```
{"action":"get","node":{"dir":true,"nodes":[{"key":"/registry","dir":true,"modifiedIndex":3,"createdIndex":3},{"key":"/bbb","value":"test","modifiedIndex":70689,"createdIndex":70689},{"key":"/111","value":"333","modifiedIndex":35380,"createdIndex":35380},{"key":"/aaa","value":"111","modifiedIndex":50991,"createdIndex":50991},{"key":"/aab","dir":true,"modifiedIndex":35980,"createdIndex":35980},{"key":"/coreos.com","dir":true,"modifiedIndex":13,"createdIndex":13}]}}
```

So I wonder where it's wrong? Thanks!

**Comment by wbwangk** [comment]
i got same response.

**Comment by xh4n3** [comment]
@hsluoyz @wbwangk 
Might be an issue with Access-Control-Allow-Origin
See if this happens:
![image](https://cloud.githubusercontent.com/assets/4469022/17760554/309c7bfa-6533-11e6-8be7-93e439840eba.png)

There're many chrome extensions to solve this, such as ForceCORS
![image](https://cloud.githubusercontent.com/assets/4469022/17760601/71d3518e-6533-11e6-91a0-e2b4a07709d2.png)

I believe if you use Docker version of etcd browser, this won't happen.

**Comment by jayunit100** [comment]
me to seeing something similar on my mac w/ request failed.  needs more debug logs (connection refused? client error?).  `curl http://127.0.0.1:2379/v2/keys` works for me, but the client running locally doesnt

**Comment by hsluoyz** [comment]
@henszey Anybody here still?

**Comment by hsluoyz** [comment]
etcd has released v3 for some time now, does this browser still work for etcd v3?

**Comment by JohnHaan** [comment]
I faced same issue even though I run through docker image.

I got below error when I see logs of the etcd-brower docker image.

root@ubuntu:~# docker logs -f etcd-browser
proxy /api requests to etcd on 183.110.81.176:4001
etc-browser listening on port 8000


events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: connect ECONNREFUSED
    at errnoException (net.js:901:11)
    at Object.afterConnect [as oncomplete] (net.js:892:19)

**Comment by freeart** [comment]
Chrome doesn't allow to use cross-domain for localhost

**Comment by lannyMa** [comment]
+1

**Comment by wadelee1986** [comment]
how  to resolve  this problem ?

**Comment by qianlnk** [comment]
thank you @xh4n3. 

my env:
docker-machine:
192.168.99.100    etcd0
192.168.99.101     etcd1
192.168.99.102    etcd2

and run etcd-browser:

```sh
docker run -d -it --name etcd-browser -p 12345:8000 --env ETCD_HOST=192.168.99.100 --env ETCD_PORT=4001 etcd-browser
```

I insalled ForceCORS and resolve this problem. here is my setting list:

setting for:
http://192.168.99.100:4001/*

|header name|header value|
|:---|:---|
|Access-Control-Allow-Origin|*|
|Access-Control-Allow-Methods|*|

**Comment by harder-worker** [comment]
To resolve this question (Request failed 404),you should edit server.js add to the values of  ca_file、key_file、cert_file.such as 
var ca_file = process.env.ETCDCTL_CA_FILE || '/etc/kubernetes/pki/etcd/ca.crt';
var key_file = process.env.ETCDCTL_KEY_FILE || '/etc/kubernetes/pki/etcd/server.key';
var cert_file = process.env.ETCDCTL_CERT_FILE || '/etc/kubernetes/pki/etcd/server.crt';

**Comment by xuyandong0822** [comment]
> To resolve this question (Request failed 404),you should edit server.js add to the values of ca_file、key_file、cert_file.such as var ca_file = process.env.ETCDCTL_CA_FILE || '/etc/kubernetes/pki/etcd/ca.crt'; var key_file = process.env.ETCDCTL_KEY_FILE || '/etc/kubernetes/pki/etcd/server.key'; var cert_file = process.env.ETCDCTL_CERT_FILE || '/etc/kubernetes/pki/etcd/server.crt';

@
